# --------------
# Docker Compose
# --------------
name: "dskgis"
services:

  djazz:
    restart: always
    image: azataiot/django-dskgis:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:16-alpine
    environment:
      - "POSTGRES_DB=dskgis"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    restart: always
    image: minio/minio
    container_name: minio
    entrypoint: sh
    command: -c 'mkdir -p /data/django-dskgis && /usr/bin/minio server /data --console-address ":9001"'
    environment:
      - "MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}"
      - "MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
  minio_data:
